name: swe
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - ld_impl_linux-64=2.44=ha97dd6f_2
  - libexpat=2.7.1=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgomp=15.2.0=h767d61c_7
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libsqlite=3.50.4=h0c1763c_0
  - libuuid=2.41.2=he9a06e4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.5.4=h26f9b46_0
  - pip=25.2=pyh8b19718_0
  - python=3.10.18=hd6af730_0_cpython
  - readline=8.2=h8c095d6_2
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=noxft_hd72426e_102
  - wheel=0.45.1=pyhd8ed1ab_1
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.0
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - anyio==4.11.0
      - async-timeout==5.0.1
      - attrs==25.4.0
      - certifi==2025.10.5
      - charset-normalizer==3.4.3
      - click==8.1.8
      - datasets==4.2.0
      - dill==0.4.0
      - distro==1.9.0
      - exceptiongroup==1.3.0
      - fastuuid==0.13.5
      - filelock==3.20.0
      - frozenlist==1.8.0
      - fsspec==2025.9.0
      - h11==0.16.0
      - hf-xet==1.1.10
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.35.3
      - idna==3.11
      - importlib-metadata==8.7.0
      - jinja2==3.1.6
      - jiter==0.11.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - linkify-it-py==2.0.3
      - litellm==1.78.0
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - mdit-py-plugins==0.5.0
      - mdurl==0.1.2
      - mini-swe-agent==1.14.2
      - multidict==6.7.0
      - multiprocess==0.70.16
      - numpy==2.2.6
      - openai==2.3.0
      - packaging==25.0
      - pandas==2.3.3
      - platformdirs==4.5.0
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - pyarrow==21.0.0
      - pydantic==2.12.0
      - pydantic-core==2.41.1
      - pygments==2.19.2
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.1
      - pytz==2025.2
      - pyyaml==6.0.3
      - referencing==0.36.2
      - regex==2025.9.18
      - requests==2.32.5
      - rich==14.2.0
      - rpds-py==0.27.1
      - sb-cli==0.1.5
      - shellingham==1.5.4
      - six==1.17.0
      - sniffio==1.3.1
      - tenacity==9.1.2
      - textual==6.3.0
      - tiktoken==0.12.0
      - tokenizers==0.22.1
      - tqdm==4.67.1
      - typer==0.19.2
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - uc-micro-py==1.0.3
      - urllib3==2.5.0
      - wcwidth==0.2.14
      - xxhash==3.6.0
      - yarl==1.22.0
      - zipp==3.23.0
prefix: /home/hojae/miniforge3/envs/swe
